### ISSUE TITLE
Component library and theming

### ISSUE THREAD

**Issue by friedjoff** [geops/react-spatial#8]
We should try to find a component library, which provides basic building blocks so we don't have to reinvent the wheel for things like buttons, links and lists. At the same time we need a theming solution to make our components more flexible. Both solutions should meet the following requirements:

* **Fast and small:** should not slow down or increase bundle size significantly.
* **Flexible:** should be easy to customize and compose with other components.
* **Easy to use:** should not require additional steps by react-spatial consumers for bundling and SSR.

### Options

* https://github.com/khan/aphrodite
* https://github.com/FormidableLabs/radium
* https://github.com/callstack/linaria
* https://github.com/styled-components/styled-components
* https://github.com/emotion-js/emotion
* https://github.com/gajus/babel-plugin-react-css-modules
* https://material-ui.com/css-in-js/basics/
* https://github.com/jxnblk/styled-system

### Options

* https://github.com/callstack/react-theme-provider
* https://github.com/airbnb/react-with-styles
* https://www.styled-components.com/docs/advanced#theming
* Custom implementation using React Context API
* Solution provided by component library

### Comparison lists

* https://gather.engineering/react-ui-frameworks-compared-dd631eb5c982
* https://hackernoon.com/the-coolest-react-ui-frameworks-for-your-new-react-app-ad699fffd651
* https://hackernoon.com/23-best-react-ui-component-libraries-and-frameworks-250a81b2ac42

### Options

* https://github.com/stardust-ui/react
* https://github.com/palantir/blueprint
* https://github.com/segmentio/evergreen
  * based on https://github.com/segmentio/ui-box
  * limited theming: https://github.com/segmentio/evergreen/issues/179
* https://github.com/mineral-ui/mineral-ui
* https://material-ui.com/

## Design Systems

* https://github.com/segmentio/ui-box
* https://github.com/rebassjs/rebass
  * provides 8 basic components as building blocks for more advanced components
  * integrates with Styled Components v4 and Emotion v10
  * based on https://github.com/jxnblk/styled-system
* https://material-ui.com/system/basics/

## Inspiration

* https://github.com/pricelinelabs/design-system
* https://www.styled-components.com/ecosystem

**Comment by oterral** [comment]
Just a thought. I like the idea using an existing libray. My only pre-requisite is: I don't want to the fight with css of this library for a line-height or a bad position value.

My ideal components lib is a component lib without css by component :)  .

**Comment by friedjoff** [comment]
I totally agree on having to fight as little as possible for CSS customization. Still wondering which component lib would give as the best balance between good out-of-the-box experience (ie. nice looking defaults, useful components) and good customization.
